In [10]:


import numpy

a_list = [2, 4, 6, 8]
new_list = []

for i in range(len(a_list)):
    add1 = 10
    nw = a_list[i] + add1
    
    new_list.append(nw)
    
    arr_list = numpy.array(new_list)
    
    print(arr_list)
    

[12]
[12 14]
[12 14 16]
[12 14 16 18]


In [81]:
import numpy as np

a_list = [2, 4, 6, 8]
new_list = []

for i in range(len(a_list)):
    add1 = 10
    a_list.append(add1)
    
    #print('new list:', a_list)
    
    arr = numpy.array(a_list)
    
    #print('array:', arr)
    
    out = np.divide(arr, 2)
    out2 = np.divide(arr, 3)
    #print('divided by 2:', out)
print('divided by 3:', out2)

divided by 3: [0.66666667 1.33333333 2.         2.66666667 3.33333333 3.33333333
 3.33333333 3.33333333]


In [36]:
a = [1, 2]
new_list = []
for i in range(len(a)):
    add1 = i
    nw = a_list[i] + add1
    
    new_list.append(nw)

In [63]:
import pandas as pd

df1 = pd.DataFrame([[117, 132, 118], [50, 32, 24], [108, 112, 115]])
print(df1)
print(df2)
df2 = pd.DataFrame([[50, 32, 24], [67, 52, 32], [84, 97, 18]])

df1.to_csv('df1.csv')
df2.to_csv('df2.csv')

frames = [df1, df2]

result = pd.concat(frames)
#print(result)

dfs_cd = pd.merge(df1, df2, how='inner')
print(dfs_cd)

dfs2_cd = pd.merge(df1, df2, how='outer')
print(dfs2_cd)

     0    1    2
0  117  132  118
1   50   32   24
2  108  112  115
    0   1   2
0  50  32  24
1  67  52  32
2  84  97  18
    0   1   2
0  50  32  24
     0    1    2
0  117  132  118
1   50   32   24
2  108  112  115
3   67   52   32
4   84   97   18


In [86]:
import numpy as np

first_matrice = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
second_matrice = np.array([[5, 3, 2], [6, 5, 3], [8, 9, 1]])

one_vector = np.array([2, 1, 0])

result_matrices = np.array([])
#for i in range(len(first_matrice)):
   
#   for j in range(len(second_matrice[0])):
#    result[i][j] = first_matrice[i][j] + second_matrice[j][i]

#for r in result:
#    print(r)
pro_of_matrice_vector = np.dot(first_matrice, one_vector)
print(pro_of_matrice_vector)
print(len(pro_of_matrice_vector))

[2 1 0]
3
